#**Project Title**

Customer Banking and Financial Analytics

#**Objective(Problem statment)**


1.  To analyze customer banking and financial data using Exploratory Data Analysis (EDA) to identify meaningful patterns, trends, and insights.
2. Data Analysis (EDA) to identify meaningful patterns, trends, and insights.
1. To understand customer demographics, account information, transaction behavior, loan details, and credit card activity.
To analyze customer feedback, complaints, suggestions, and resolution status to understand customer service experience and satisfaction.
2. To clean, transform, and preprocess the data to make it suitable for analysis and visualization.
1. To create meaningful visualizations using Python and an interactive dashboard using Power BI to support data-driven decision-making.
1. To provide actionable insights and recommendations that can help the business improve customer experience and overall service performance.

#**Outcome**

The project delivers a comprehensive view of customer banking and financial activity by uncovering meaningful patterns across customer profiles, account balances, transactions, loans, credit card usage, and customer feedback.

Through Python-based data analysis and an interactive Power BI dashboard, the project transforms raw banking data into actionable business insights, enabling stakeholders to understand customer behavior, identify financial trends, evaluate service performance, improve customer experience, and support informed, data-driven decision-making.

#**Domain**

Banking and Financial Services

#**Dataset Information**

**Source:** https://github.com/ahsan084/Banking-Dataset/blob/main/Comprehensive_Banking_Database.csv

**Original Dataset Size:** 5,000 rows × 40 columns

**Dataset Used for Analysis:** 5,000 rows × 20 selected columns

**Year / Timeline:** The dataset covers the period from 2000 to 2023. Account opening records span from 2000 to 2022, while transaction, credit card, payment, and customer feedback activities are primarily recorded during 2023.

**Format:** CSV

**Dataset Column/features Description:**

* **Customer ID** - Unique identification number assigned to each customer.

* **Age** - Age of the customer.

* **Gender** - Gender of the customer.

* **City** - City associated with the customer.

* **Account Type** - Type of bank account held by the customer.

* **Account Balance** - Current balance maintained in the customer's bank account.

* **Date Of Account Opening** - Date on which the customer's bank account was opened.

* **Transaction Date** - Date on which the banking transaction occurred.

* **Transaction Type** - Type or category of banking transaction.

* **Transaction Amount** - Monetary amount involved in the transaction.

* **Loan Type** - Type of loan associated with the customer.

* **Loan Amount** - Monetary amount associated with the customer's loan.

* **Interest Rate** - Interest rate applicable to the customer's loan.

* **Loan Status** - Current status of the loan, such as approval or rejection status.

* **Card Type** - Type of credit card held by the customer.

* **Credit Limit** - Maximum credit limit available on the customer's credit card.

* **Credit Card Balance** - Outstanding balance on the customer's credit card.

* **Feedback Type** - Category or type of feedback provided by the customer.

* **Resolution Status** - Status indicating whether the customer's feedback or issue has been resolved.

* **Anomaly** - Indicates whether the customer's transaction or activity is considered normal (1) or anomalous/unusual (-1).

#Stages for DA Project

##Stage 1 – Problem Definition and Dataset Selection

* **Business Problem and Expected Outcome**

The objective is to analyze customer banking and financial data to understand customer profiles, account activity, transaction behavior, loan performance, credit card usage, and customer feedback.

The analysis will help identify meaningful patterns and trends in customer financial activity, understand banking and credit-related behavior, and evaluate customer feedback and resolution patterns. The findings will be used to generate actionable insights and support data-driven decision-making through Python analysis and an interactive Power BI dashboard.

* **Dataset Selection**

The Customer Banking Dataset is selected for this project. It contains 5,000 customer records with 40 features covering customer demographics, account information, transactions, loans, credit cards, and customer feedback.

For this analysis, 18 relevant features will be selected from the original 40 columns based on the project objectives. The selected working dataset will contain 5,000 records and 18 analytical columns, covering customer demographics, account details, transaction activity, loan information, credit card usage, and customer feedback.

* **Source:** https://github.com/ahsan084/Banking-Dataset/blob/main/Comprehensive_Banking_Database.csv

#**Inital EDA**

**Import Required Libraries**

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

Load Dataset

In [57]:
url = "https://raw.githubusercontent.com/madhubalaselvaraj25-cell/Customer-Banking-Financial-Analytics-Using-Python-and-Power-BI/refs/heads/main/Customer%20Banking%20Database_rawdata.csv"
df = pd.read_csv(url)

In [58]:
df.head()

,Customer ID,First Name,Last Name,Age,Gender,Address,City,Contact Number,Email,Account Type,...,Minimum Payment Due,Payment Due Date,Last Credit Card Payment Date,Rewards Points,Feedback ID,Feedback Date,Feedback Type,Resolution Status,Resolution Date,Anomaly
0,1,Joshua,Hall,45,Male,Address_1,Fort Worth,19458794854,joshua.hall@kag.com,Current,...,226.22,11/26/2023,3/20/2023,8142,1,10/6/2023,Suggestion,Resolved,1/22/2023,1
1,2,Mark,Taylor,47,Female,Address_2,Louisville,19458794855,mark.taylor@kag.com,Current,...,42.84,11/5/2023,6/16/2023,4306,2,4/7/2023,Complaint,Resolved,8/27/2023,1
2,3,Joseph,Flores,25,Female,Address_3,Philadelphia,19458794856,joseph.flores@kag.com,Current,...,162.12,1/8/2023,3/20/2023,4842,3,9/7/2023,Praise,Pending,5/11/2023,1
3,4,Kevin,Lee,52,Other,Address_4,Oklahoma City,19458794857,kevin.lee@kag.com,Savings,...,216.46,9/8/2023,10/15/2023,9463,4,5/28/2023,Complaint,Resolved,7/5/2023,1
4,5,Linda,Johnson,68,Other,Address_5,Phoenix,19458794858,linda.johnson@kag.com,Savings,...,1.29,3/4/2023,7/27/2023,2209,5,2/12/2023,Complaint,Resolved,11/21/2023,1

In [59]:
# Dataset Shape

df.shape

(5000, 40)

In [60]:
# Dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 40 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        5000 non-null   int64
 1   First Name                         5000 non-null   object
 2   Last Name                          5000 non-null   object
 3   Age                                5000 non-null   int64
 4   Gender                             5000 non-null   object
 5   Address                            5000 non-null   object
 6   City                               5000 non-null   object
 7   Contact Number                     5000 non-null   int64
 8   Email                              5000 non-null   object
 9   Account Type                       5000 non-null   object
 10  Account Balance                    5000 non-null   float64
 11  Date Of Account Opening            5000 non-null   object
 12  Last Transaction Date              5000 non-null   object
 13  TransactionID                      5000 non-null   int64
 14  Transaction Date                   5000 non-null   object
 15  Transaction Type                   5000 non-null   object
 16  Transaction Amount                 5000 non-null   float64
 17  Account Balance After Transaction  5000 non-null   float64
 18  Branch ID                          5000 non-null   int64
 19  Loan ID                            5000 non-null   int64
 20  Loan Amount                        5000 non-null   float64
 21  Loan Type                          5000 non-null   object
 22  Interest Rate                      5000 non-null   float64
 23  Loan Term                          5000 non-null   int64
 24  Approval/Rejection Date            5000 non-null   object
 25  Loan Status                        5000 non-null   object
 26  CardID                             5000 non-null   int64
 27  Card Type                          5000 non-null   object
 28  Credit Limit                       5000 non-null   float64
 29  Credit Card Balance                5000 non-null   float64
 30  Minimum Payment Due                5000 non-null   float64
 31  Payment Due Date                   5000 non-null   object
 32  Last Credit Card Payment Date      5000 non-null   object
 33  Rewards Points                     5000 non-null   int64
 34  Feedback ID                        5000 non-null   int64
 35  Feedback Date                      5000 non-null   object
 36  Feedback Type                      5000 non-null   object
 37  Resolution Status                  5000 non-null   object
 38  Resolution Date                    5000 non-null   object
 39  Anomaly                            5000 non-null   int64
dtypes: float64(8), int64(11), object(21)
memory usage: 1.5+ MB

In [61]:
# Column Names

df.columns

Index(['Customer ID', 'First Name', 'Last Name', 'Age', 'Gender', 'Address',
       'City', 'Contact Number', 'Email', 'Account Type', 'Account Balance',
       'Date Of Account Opening', 'Last Transaction Date', 'TransactionID',
       'Transaction Date', 'Transaction Type', 'Transaction Amount',
       'Account Balance After Transaction', 'Branch ID', 'Loan ID',
       'Loan Amount', 'Loan Type', 'Interest Rate', 'Loan Term',
       'Approval/Rejection Date', 'Loan Status', 'CardID', 'Card Type',
       'Credit Limit', 'Credit Card Balance', 'Minimum Payment Due',
       'Payment Due Date', 'Last Credit Card Payment Date', 'Rewards Points',
       'Feedback ID', 'Feedback Date', 'Feedback Type', 'Resolution Status',
       'Resolution Date', 'Anomaly'],
      dtype='object')

In [62]:
# Statistical Summary

df.describe()

,Customer ID,Age,Contact Number,Account Balance,TransactionID,Transaction Amount,Account Balance After Transaction,Branch ID,Loan ID,Loan Amount,Interest Rate,Loan Term,CardID,Credit Limit,Credit Card Balance,Minimum Payment Due,Rewards Points,Feedback ID,Anomaly
count,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,43.469800,1.945880e+10,5060.570918,2500.500000,2508.501144,5037.418898,50.586800,2500.500000,25501.042806,5.505038,36.520800,2500.500000,5549.035830,2487.40084,124.370134,4966.161800,2500.500000,0.880000
std,1443.520003,15.145672,1.443520e+03,2849.356481,1443.520003,1450.194986,4053.220017,28.499539,1443.520003,14039.732628,2.629752,16.924315,1443.520003,2581.718105,1446.80295,72.340102,2901.410915,1443.520003,0.475021
min,1.000000,18.000000,1.945879e+10,107.200000,1.000000,10.570000,-4878.760000,1.000000,1.000000,1006.370000,1.000000,12.000000,1.000000,1007.000000,1.45000,0.070000,1.000000,1.000000,-1.000000
25%,1250.750000,30.000000,1.945880e+10,2582.777500,1250.750000,1241.150000,2047.205000,26.000000,1250.750000,13315.305000,3.200000,24.000000,1250.750000,3314.065000,1243.51750,62.180000,2475.250000,1250.750000,1.000000
50%,2500.500000,43.000000,1.945880e+10,5075.500000,2500.500000,2494.025000,5089.785000,50.000000,2500.500000,25909.705000,5.520000,36.000000,2500.500000,5567.485000,2461.62000,123.080000,4950.500000,2500.500000,1.000000
75%,3750.250000,57.000000,1.945880e+10,7509.760000,3750.250000,3796.222500,8036.367500,75.000000,3750.250000,37441.570000,7.832500,48.000000,3750.250000,7786.040000,3722.58000,186.125000,7483.250000,3750.250000,1.000000
max,5000.000000,69.000000,1.945880e+10,9998.110000,5000.000000,4998.390000,14911.380000,99.000000,5000.000000,49993.490000,10.000000,60.000000,5000.000000,9997.780000,4997.11000,249.860000,9999.000000,5000.000000,1.000000

In [63]:
# Check Missing Values

df.isnull().sum()

Customer ID                          0
First Name                           0
Last Name                            0
Age                                  0
Gender                               0
Address                              0
City                                 0
Contact Number                       0
Email                                0
Account Type                         0
Account Balance                      0
Date Of Account Opening              0
Last Transaction Date                0
TransactionID                        0
Transaction Date                     0
Transaction Type                     0
Transaction Amount                   0
Account Balance After Transaction    0
Branch ID                            0
Loan ID                              0
Loan Amount                          0
Loan Type                            0
Interest Rate                        0
Loan Term                            0
Approval/Rejection Date              0
Loan Status                          0
CardID                               0
Card Type                            0
Credit Limit                         0
Credit Card Balance                  0
Minimum Payment Due                  0
Payment Due Date                     0
Last Credit Card Payment Date        0
Rewards Points                       0
Feedback ID                          0
Feedback Date                        0
Feedback Type                        0
Resolution Status                    0
Resolution Date                      0
Anomaly                              0
dtype: int64

In [64]:
# Duplicate Record Check

df.duplicated().sum()

np.int64(0)

In [66]:
# Select the 20 Features for Analysis

selected_columns = ['Customer ID','Age','Gender',
                   'City','Account Type',
                   'Account Balance','Date Of Account Opening',
                   'Transaction Date','Transaction Type',
                   'Transaction Amount','Account Balance After Transaction',
                   'Loan Type','Loan Amount','Interest Rate','Loan Status',
                   'Card Type','Credit Card Balance',
                   'Feedback Type','Resolution Status','Anomaly']

In [67]:
df.analysis=df[selected_columns].copy()

df.analysis.head()

,Customer ID,Age,Gender,City,Account Type,Account Balance,Date Of Account Opening,Transaction Date,Transaction Type,Transaction Amount,Account Balance After Transaction,Loan Type,Loan Amount,Interest Rate,Loan Status,Card Type,Credit Card Balance,Feedback Type,Resolution Status,Anomaly
0,1,45,Male,Fort Worth,Current,1313.38,5/26/2006,12/7/2023,Withdrawal,1457.61,2770.99,Mortgage,32200.06,2.64,Rejected,AMEX,4524.32,Suggestion,Resolved,1
1,2,47,Female,Louisville,Current,5988.46,3/2/2006,4/27/2023,Deposit,1660.99,7649.45,Auto,47743.52,2.48,Approved,MasterCard,856.70,Complaint,Resolved,1
2,3,25,Female,Philadelphia,Current,8277.88,7/19/2015,4/5/2023,Deposit,839.91,7437.97,Auto,47981.31,7.84,Closed,AMEX,3242.36,Praise,Pending,1
3,4,52,Other,Oklahoma City,Savings,7487.21,1/30/2008,7/28/2023,Withdrawal,4908.89,12396.10,Personal,4482.80,7.21,Approved,MasterCard,4329.17,Complaint,Resolved,1
4,5,68,Other,Phoenix,Savings,6993.55,5/25/2021,1/16/2023,Transfer,589.07,6404.48,Mortgage,1092.33,5.37,Approved,Visa,25.72,Complaint,Resolved,1

In [68]:
# Check Selected Dataset Shape

df.analysis.shape

(5000, 20)

In [69]:
# Selected Dataset Information

df.analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        5000 non-null   int64
 1   Age                                5000 non-null   int64
 2   Gender                             5000 non-null   object
 3   City                               5000 non-null   object
 4   Account Type                       5000 non-null   object
 5   Account Balance                    5000 non-null   float64
 6   Date Of Account Opening            5000 non-null   object
 7   Transaction Date                   5000 non-null   object
 8   Transaction Type                   5000 non-null   object
 9   Transaction Amount                 5000 non-null   float64
 10  Account Balance After Transaction  5000 non-null   float64
 11  Loan Type                          5000 non-null   object
 12  Loan Amount                        5000 non-null   float64
 13  Interest Rate                      5000 non-null   float64
 14  Loan Status                        5000 non-null   object
 15  Card Type                          5000 non-null   object
 16  Credit Card Balance                5000 non-null   float64
 17  Feedback Type                      5000 non-null   object
 18  Resolution Status                  5000 non-null   object
 19  Anomaly                            5000 non-null   int64
dtypes: float64(6), int64(3), object(11)
memory usage: 781.4+ KB

In [70]:
# Statistical Summary of Selected Dataset

df.analysis.describe()

,Customer ID,Age,Account Balance,Transaction Amount,Account Balance After Transaction,Loan Amount,Interest Rate,Credit Card Balance,Anomaly
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000
mean,2500.500000,43.469800,5060.570918,2508.501144,5037.418898,25501.042806,5.505038,2487.40084,0.880000
std,1443.520003,15.145672,2849.356481,1450.194986,4053.220017,14039.732628,2.629752,1446.80295,0.475021
min,1.000000,18.000000,107.200000,10.570000,-4878.760000,1006.370000,1.000000,1.45000,-1.000000
25%,1250.750000,30.000000,2582.777500,1241.150000,2047.205000,13315.305000,3.200000,1243.51750,1.000000
50%,2500.500000,43.000000,5075.500000,2494.025000,5089.785000,25909.705000,5.520000,2461.62000,1.000000
75%,3750.250000,57.000000,7509.760000,3796.222500,8036.367500,37441.570000,7.832500,3722.58000,1.000000
max,5000.000000,69.000000,9998.110000,4998.390000,14911.380000,49993.490000,10.000000,4997.11000,1.000000

In [71]:
# Check Missing Values

df.isnull().sum()

Customer ID                          0
First Name                           0
Last Name                            0
Age                                  0
Gender                               0
Address                              0
City                                 0
Contact Number                       0
Email                                0
Account Type                         0
Account Balance                      0
Date Of Account Opening              0
Last Transaction Date                0
TransactionID                        0
Transaction Date                     0
Transaction Type                     0
Transaction Amount                   0
Account Balance After Transaction    0
Branch ID                            0
Loan ID                              0
Loan Amount                          0
Loan Type                            0
Interest Rate                        0
Loan Term                            0
Approval/Rejection Date              0
Loan Status                          0
CardID                               0
Card Type                            0
Credit Limit                         0
Credit Card Balance                  0
Minimum Payment Due                  0
Payment Due Date                     0
Last Credit Card Payment Date        0
Rewards Points                       0
Feedback ID                          0
Feedback Date                        0
Feedback Type                        0
Resolution Status                    0
Resolution Date                      0
Anomaly                              0
dtype: int64

In [72]:
# Check Duplicate Records in Selected Dataset

df.analysis.duplicated().sum()

np.int64(0)

##Stage 2 – Data Cleaning and Pre-processing

In [82]:
# Create a clean working copy

df_clean = df.analysis.copy()

df_clean.head()

,Customer ID,Age,Gender,City,Account Type,Account Balance,Date Of Account Opening,Transaction Date,Transaction Type,Transaction Amount,Account Balance After Transaction,Loan Type,Loan Amount,Interest Rate,Loan Status,Card Type,Credit Card Balance,Feedback Type,Resolution Status,Anomaly
0,1,45,Male,Fort Worth,Current,1313.38,5/26/2006,12/7/2023,Withdrawal,1457.61,2770.99,Mortgage,32200.06,2.64,Rejected,AMEX,4524.32,Suggestion,Resolved,1
1,2,47,Female,Louisville,Current,5988.46,3/2/2006,4/27/2023,Deposit,1660.99,7649.45,Auto,47743.52,2.48,Approved,MasterCard,856.70,Complaint,Resolved,1
2,3,25,Female,Philadelphia,Current,8277.88,7/19/2015,4/5/2023,Deposit,839.91,7437.97,Auto,47981.31,7.84,Closed,AMEX,3242.36,Praise,Pending,1
3,4,52,Other,Oklahoma City,Savings,7487.21,1/30/2008,7/28/2023,Withdrawal,4908.89,12396.10,Personal,4482.80,7.21,Approved,MasterCard,4329.17,Complaint,Resolved,1
4,5,68,Other,Phoenix,Savings,6993.55,5/25/2021,1/16/2023,Transfer,589.07,6404.48,Mortgage,1092.33,5.37,Approved,Visa,25.72,Complaint,Resolved,1

In [73]:
# Handle Missing Values

In [83]:
# Check Missing Values

missing_values = df_clean.isnull().sum()

In [84]:
missing_values[missing_values > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [85]:
# Check Missing Value Percentage

missing_percentage =  (df_clean.isnull().sum() / len(df)) * 100

missing_percentage[missing_percentage>0].sort_values(ascending=False)

Series([], dtype: float64)

In [77]:
# Handle Duplicates

In [86]:
# Check Duplicate Rows

df_clean.duplicated().sum()

np.int64(0)

In [79]:
# Rename / Drop Unwanted Columns

In [87]:
# Display Selected Columns

df_clean.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'City',
 'Account Type',
 'Account Balance',
 'Date Of Account Opening',
 'Transaction Date',
 'Transaction Type',
 'Transaction Amount',
 'Account Balance After Transaction',
 'Loan Type',
 'Loan Amount',
 'Interest Rate',
 'Loan Status',
 'Card Type',
 'Credit Card Balance',
 'Feedback Type',
 'Resolution Status',
 'Anomaly']

In [88]:
# Rename columns for consistency and readability

df_clean = df_clean.rename(columns={
    "Customer ID": "Customer_ID",
    "Account Type": "Account_Type",
    "Account Balance": "Account_Balance",
    "Date Of Account Opening": "Account_Opening_Date",
    "Transaction Date": "Transaction_Date",
    "Transaction Type": "Transaction_Type",
    "Transaction Amount": "Transaction_Amount",
    "Account Balance After Transaction": "Balance_After_Transaction",
    "Loan Type": "Loan_Type",
    "Loan Amount": "Loan_Amount",
    "Interest Rate": "Interest_Rate",
    "Loan Status": "Loan_Status",
    "Card Type": "Card_Type",
    "Credit Card Balance": "Credit_Card_Balance",
    "Feedback Type": "Feedback_Type",
    "Resolution Status": "Resolution_Status"
})

In [89]:
df_clean.columns.tolist()

['Customer_ID',
 'Age',
 'Gender',
 'City',
 'Account_Type',
 'Account_Balance',
 'Account_Opening_Date',
 'Transaction_Date',
 'Transaction_Type',
 'Transaction_Amount',
 'Balance_After_Transaction',
 'Loan_Type',
 'Loan_Amount',
 'Interest_Rate',
 'Loan_Status',
 'Card_Type',
 'Credit_Card_Balance',
 'Feedback_Type',
 'Resolution_Status',
 'Anomaly']

In [90]:
# Convert Data Types

In [92]:
# Check current data types

df_clean.dtypes

Customer_ID                    int64
Age                            int64
Gender                        object
City                          object
Account_Type                  object
Account_Balance              float64
Account_Opening_Date          object
Transaction_Date              object
Transaction_Type              object
Transaction_Amount           float64
Balance_After_Transaction    float64
Loan_Type                     object
Loan_Amount                  float64
Interest_Rate                float64
Loan_Status                   object
Card_Type                     object
Credit_Card_Balance          float64
Feedback_Type                 object
Resolution_Status             object
Anomaly                        int64
dtype: object

In [93]:
# Convert date columns to datetime format

df_clean['Account_Opening_Date'] = pd.to_datetime(
    df_clean['Account_Opening_Date'],
    errors='coerce'
)
df_clean['Transaction_Date'] = pd.to_datetime(
    df_clean['Transaction_Date'],
    errors='coerce'
)

In [97]:
df_clean[['Account_Opening_Date','Transaction_Date']].dtypes

Account_Opening_Date    datetime64[ns]
Transaction_Date        datetime64[ns]
dtype: object

In [98]:
# Check for invalid dates after conversion

df_clean[['Account_Opening_Date', 'Transaction_Date']].isnull().sum()

Account_Opening_Date    0
Transaction_Date        0
dtype: int64

In [99]:
# Check Data Consistency

In [111]:
# Check unique values in important categorical columns

categorical_columns = [
    'Gender',
    'City',
    'Account_Type',
    'Loan_Type',
    'Loan_Status',
    'Feedback_Type',
    'Resolution_Status',
    'Anomaly'
]

for col in categorical_columns:
  print(f"\n{col}")
  print(df_clean[col].unique())

Gender
['Male' 'Female' 'Other']

City
['Fort Worth' 'Louisville' 'Philadelphia' 'Oklahoma City' 'Phoenix'
 'El Paso' 'Dallas' 'Memphis' 'Indianapolis' 'Washington' 'San Diego'
 'Columbus' 'Colorado Springs' 'Atlanta' 'Fresno' 'Austin' 'Omaha'
 'Tucson' 'Milwaukee' 'San Antonio' 'Boston' 'Chicago' 'Kansas City'
 'Baltimore' 'San Francisco' 'Jacksonville' 'Sacramento' 'Seattle'
 'Portland' 'Mesa' 'Albuquerque' 'Nashville' 'Denver' 'New York'
 'Las Vegas' 'Houston' 'San Jose' 'Los Angeles' 'Charlotte' 'Detroit']

Account_Type
['Current' 'Savings']

Loan_Type
['Mortgage' 'Auto' 'Personal']

Loan_Status
['Rejected' 'Approved' 'Closed']

Feedback_Type
['Suggestion' 'Complaint' 'Praise']

Resolution_Status
['Resolved' 'Pending']

Anomaly
[ 1 -1]

In [109]:
#  Treat Outliers

In [114]:
# Numerical variables selected for outlier analysis

numeric_columns = [
    'Age',
    'Account_Balance',
    'Transaction_Amount',
    'Balance_After_Transaction',
    'Loan_Amount',
    'Interest_Rate',
    'Credit_Card_Balance'
]

# Statistical summary

df_clean[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Age,5000.0,43.469800,15.145672,18.00,30.0000,43.000,57.0000,69.00
Account_Balance,5000.0,5060.570918,2849.356481,107.20,2582.7775,5075.500,7509.7600,9998.11
Transaction_Amount,5000.0,2508.501144,1450.194986,10.57,1241.1500,2494.025,3796.2225,4998.39
Balance_After_Transaction,5000.0,5037.418898,4053.220017,-4878.76,2047.2050,5089.785,8036.3675,14911.38
Loan_Amount,5000.0,25501.042806,14039.732628,1006.37,13315.3050,25909.705,37441.5700,49993.49
Interest_Rate,5000.0,5.505038,2.629752,1.00,3.2000,5.520,7.8325,10.00
Credit_Card_Balance,5000.0,2487.400840,1446.802950,1.45,1243.5175,2461.620,3722.5800,4997.11

In [119]:
# Check outliers using IQR method

for col in numeric_columns:

  Q1 = df_clean[col].quantile(0.25)
  Q3 = df_clean[col].quantile(0.75)
  IQR = Q3-Q1

  lower_bond = Q1 - 1.5 * IQR
  upper_bond = Q3 + 1.5 * IQR

  outliers = (
      (df_clean[col] < lower_bond)|
      (df_clean[col]> upper_bond)
  ).sum()

  print(f"\n{col}:{outliers} outliers")

Age:0 outliers

Account_Balance:0 outliers

Transaction_Amount:0 outliers

Balance_After_Transaction:0 outliers

Loan_Amount:0 outliers

Interest_Rate:0 outliers

Credit_Card_Balance:0 outliers

### Outlier Detection Results

The IQR method was applied to the numerical columns: Age, Account_Balance, Transaction_Amount, Balance_After_Transaction, Loan_Amount, Interest_Rate, and Credit_Card_Balance.

No outliers were detected in any of the numerical columns. Therefore, no outlier treatment or removal was performed based on the IQR method.

In [118]:
# Check Skewness and Apply Transformations

In [120]:
# Check skewness of numerical variables

skewness = df_clean[numeric_columns].skew()

skewness.sort_values(ascending=False)

Credit_Card_Balance          0.025690
Transaction_Amount           0.011889
Age                          0.011710
Balance_After_Transaction   -0.003499
Interest_Rate               -0.015234
Account_Balance             -0.015587
Loan_Amount                 -0.016204
dtype: float64

## Skewness Analysis

Skewness was calculated for the numerical variables to understand the symmetry of their distributions.

The skewness values for all numerical variables are very close to zero, indicating that the variables are approximately symmetrically distributed. No significant positive or negative skewness was observed.

In [121]:
# Feature Transformations

In [123]:
# Extract transaction year

df_clean['Transaction_Year'] = df_clean['Transaction_Date'].dt.year

In [125]:
# Extract transaction month

df_clean['Transaction_Month'] = df_clean['Transaction_Date'].dt.month

In [127]:
# Extract transaction month name

df_clean['Transaction_Month_Name'] = df_clean['Transaction_Date'].dt.month_name()

In [128]:
# Extract account opening year

df_clean["Account_Opening_Year"] = df_clean['Account_Opening_Date'].dt.year

In [133]:
df_clean[
    [
        'Transaction_Date',
        'Transaction_Year',
        'Transaction_Month',
        'Transaction_Month_Name',
        'Account_Opening_Year'
    ]
].head()

,Transaction_Date,Transaction_Year,Transaction_Month,Transaction_Month_Name,Account_Opening_Year
0,2023-12-07,2023,12,December,2006
1,2023-04-27,2023,4,April,2006
2,2023-04-05,2023,4,April,2015
3,2023-07-28,2023,7,July,2008
4,2023-01-16,2023,1,January,2021

In [134]:
# Final Data Validation

In [136]:
# Check final dataset dimensions

df_clean.shape

(5000, 24)

In [138]:
# Final missing-value check

df_clean.isnull().sum().sum()

np.int64(0)

In [139]:
# Final duplicate check

df_clean.duplicated().sum()

np.int64(0)

In [141]:
df_clean.dtypes

Customer_ID                           int64
Age                                   int64
Gender                               object
City                                 object
Account_Type                         object
Account_Balance                     float64
Account_Opening_Date         datetime64[ns]
Transaction_Date             datetime64[ns]
Transaction_Type                     object
Transaction_Amount                  float64
Balance_After_Transaction           float64
Loan_Type                            object
Loan_Amount                         float64
Interest_Rate                       float64
Loan_Status                          object
Card_Type                            object
Credit_Card_Balance                 float64
Feedback_Type                        object
Resolution_Status                    object
Anomaly                               int64
Transaction_Year                      int32
Transaction_Month                     int32
Transaction_Month_Name               object
Account_Opening_Year                  int32
dtype: object

In [142]:
# Display final dataset

df_clean.head()

,Customer_ID,Age,Gender,City,Account_Type,Account_Balance,Account_Opening_Date,Transaction_Date,Transaction_Type,Transaction_Amount,...,Loan_Status,Card_Type,Credit_Card_Balance,Feedback_Type,Resolution_Status,Anomaly,Transaction_Year,Transaction_Month,Transaction_Month_Name,Account_Opening_Year
0,1,45,Male,Fort Worth,Current,1313.38,2006-05-26,2023-12-07,Withdrawal,1457.61,...,Rejected,AMEX,4524.32,Suggestion,Resolved,1,2023,12,December,2006
1,2,47,Female,Louisville,Current,5988.46,2006-03-02,2023-04-27,Deposit,1660.99,...,Approved,MasterCard,856.70,Complaint,Resolved,1,2023,4,April,2006
2,3,25,Female,Philadelphia,Current,8277.88,2015-07-19,2023-04-05,Deposit,839.91,...,Closed,AMEX,3242.36,Praise,Pending,1,2023,4,April,2015
3,4,52,Other,Oklahoma City,Savings,7487.21,2008-01-30,2023-07-28,Withdrawal,4908.89,...,Approved,MasterCard,4329.17,Complaint,Resolved,1,2023,7,July,2008
4,5,68,Other,Phoenix,Savings,6993.55,2021-05-25,2023-01-16,Transfer,589.07,...,Approved,Visa,25.72,Complaint,Resolved,1,2023,1,January,2021